apiVersion: apps/v1
kind: Deployment
metadata:
  name: neosec-files-server
  labels:
    app: python-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: neosec:0.0.1
          env:
            - name: DIRECTORY
              value: {{ .Values.app.directory }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: files-volume
              mountPath: /app/files
      volumes:
        - name: files-volume
          configMap:
            name: python-app-files