name: NeoSec Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/app:latest
  
  deployHelm:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'  # Clone Repo
        uses: 'actions/checkout@v1'

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'
        id: install


      - name: Set AWS Profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: aws-profile
          region: us-east-1
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Config File
        run: |
            echo $KUBECONFIG_FILE > config
        shell: bash
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'

      # - name: deploy
      #   uses: craftech-io/eks-helm-deploy-action@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      #     cluster-name: neosec-exercise
      #     config-files: ./charts/values.yaml
      #     chart-path: ./charts/
      #     namespace: yuvalpress
      #     name: yuvalpress-app

      # - name: Helm on EKS (with eksctl)
      #   uses: tensor-hq/eksctl-helm-action@0.1.0
      #   with:
      #     # Your command (kubectl or helm)
      #     command: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml --kubeconfig config
      #     # Name of your EKS cluster (i.e., from `eksctl get cluster`)
      #     eks_cluster: neosec-exercise

      - name: Deploy To Cluster
        run: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml --kubeconfig config
        
