name: NeoSec Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/app:latest
  
  deployHelm:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'  # Clone Repo
        uses: 'actions/checkout@v1'

      - name: Install Helm
        uses: azure/setup-helm@v1
        id: install

      - name: AWS CLI Install
        run: sudo apt update && sudo apt install awscli -y

      - name: Configure AWS credentials for EKS deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Write profile aws
        run: echo "[aws-profile]\nregion = us-east-1" > ~/.aws/config

      - name: Setup kubeconfig
        id: setup-kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name neosec-exercise

      - name: check
        run: cat ~/.aws/config

      - name: check
        run: cat ~/.aws/credentials

      # - name: Create Config File
      #   run: |
      #       echo "$KUBECONFIG_FILE" > config
      #       cat config | base64 -d > config
      #   shell: bash
      #   env:
      #     KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'

      # - name: deploy
      #   uses: craftech-io/eks-helm-deploy-action@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      #     cluster-name: arn:aws:eks:us-east-1:064274872851:cluster/neosec-exercise
      #     config-files: ./charts/values.yaml
      #     chart-path: ./charts/
      #     namespace: yuvalpress
      #     name: yuvalpress-app

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml
          # kubeconfig: '${{ secrets.KUBE_CONFIG }}'


      # - name: Helm on EKS (with eksctl)
      #   uses: tensor-hq/eksctl-helm-action@0.1.0
      #   with:
      #     # Your command (kubectl or helm)
      #     command: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml --kubeconfig config
      #     # Name of your EKS cluster (i.e., from `eksctl get cluster`)
      #     eks_cluster: neosec-exercise

      # - name: Export Kube Config
      #   run: |
      #     kubectl config view --raw >./config1
      #     cat config

      - name: Create Namespace
        run: kubectl create ns yuvalpress | true

      # - name: Deploy To Cluster
      #   run: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml --kubeconfig=./config
        
