name: NeoSec Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/app:latest
  
  deployHelm:
    runs-on: ubuntu-latest

    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
     AWS_REGION: ${{ secrets.AWS_REGION }}
    
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v1
        id: install

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'

      - name: aws configure profile
        run: aws configure set --profile ${{ secrets.AWS_PROFILE }} region ${{ secrets.AWS_REGION }}
        shell: bash

      - name: Create Namespace
        run: kubectl create namespace yuvalpress || true

      - name: Deploy To Cluster
        run: helm upgrade --install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml