name: NeoSec Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/app:latest
  
  deployHelm:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'  # Clone Repo
        uses: 'actions/checkout@v1'

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'
        id: install

      - name: Deploy To Cluster
        run: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml --kubeconfig "$KUBECONFIG_FILE"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
        
      # - name: Deploy Helm To Kubernetes
      #   uses: 'deliverybot/helm@master'
      #   with:
      #     token: '${{ github.token }}'        
      #     chart: 'neosec'
      #     namespace: yuvalpress
      #     release: yuvalpress-python-app
      #     value-files: './charts/values.yaml'
      #   env:
      #     KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
