name: NeoSec Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/app:latest
  
  deployHelm:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'  # Clone Repo
        uses: 'actions/checkout@v1'

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Config File
        run: |
            echo $KUBECONFIG_FILE > config
            cat config | base64 -d > config
            mv -f config ~/.kube/config
        shell: bash
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'

      # - name: Deploy Chart To EKS
      #   uses: peymanmortazavi/eks-helm-deploy@v2.1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east1
      #     cluster-name: neosec-exercise
      #     config-files: ./charts/values.yaml
      #     namespace: yuvalpress
      #     name: yuvalpress-app
      #     chart-path: ./charts/

      - name: Helm on EKS (with eksctl)
        uses: tensor-hq/eksctl-helm-action@0.1.0
        with:
          # Your command (kubectl or helm)
          command: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml --kubeconfig config
          # Name of your EKS cluster (i.e., from `eksctl get cluster`)
          eks_cluster: neosec-exercise

      # - name: Deploy To Cluster
      #   run: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml --kubeconfig config
        
      # - name: Deploy Helm To Kubernetes
      #   uses: 'deliverybot/helm@master'
      #   with:
      #     token: '${{ github.token }}'        
      #     chart: './charts/neosec'
      #     namespace: yuvalpress
      #     release: yuvalpress-app
      #     value-files: './charts/values.yaml'
      #   env:
      #     KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
