name: NeoSec Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/app:latest
  
  deployHelm:
    runs-on: ubuntu-latest

    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     AWS-PROFILE: aws-profile
     AWS-REGION: us-east-1
    
    steps:
      - uses: actions/checkout@v2

      # - name: AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: AWS Profile Set
      #   uses: Fooji/create-aws-profile-action@v1
      #   with:
      #     profile: aws-profile
      #     region: us-east-1

      - uses: azure/setup-helm@v1
        id: install

      # - name: helm deploy
      #   uses: koslibpro/helm-eks-action@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     command: helm install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml


      # - name: AWS CLI Install
      #   run: sudo apt update && sudo apt install awscli -y

      - name: Setup kubeconfig
        id: setup-kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name neosec-exercise

      - name: Create Namespace
        run: kubectl create ns yuvalpress | true

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: |
            apiVersion: v1
            clusters:
            - cluster:
                certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EUXhPREV3TlRRME0xb1hEVE15TURReE5URXdOVFEwTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUdFCnBpcHE3NldSMkZ5WndzaUsvbTlZVE44OWJMaFJEcTJZY09WSWYyQ3Z1YnlFV2FPcTJhY2FIY2RHMXFsVVFIa0kKRTVYTVJ6SHFMYjYya2dvWEZnbTlHV0N5cVEvRXA1TkVKRnVEVzBHWSt1Yk12QW9NQmVZU1ZRWmhmaHJSVkdXZwp6R0lEOEV5T3VXZlltVVNhYm5nYU9kRk5ITVRJUnExZlpZUmRIQnBndDh4R3NrclYwY3JBcmRHSm95RS9aRFhiCkNJeW15OGdUdXNPRStWbkQxM1pzSFlJWHJRbHpmRlR4NnBvZmlpMUtqRXl6b3ZRaHkvVnR5U1QrV3h2UU1mSk8KN0ExaXc5SXdPQWFIWmlZYlpGMERmUnNyNzNDV05BdGVUa3NVendFMDJobHNrKy8veWRNTS9QQnZiWTFWMHEvMApROTRwZ3c1aFpXOElpL3ZzUEpFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHQ1NOYXdEQnRRN21sUW1ZdUhtRXFiYXp6SmNNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDQjlZRXNSU1A2Qk1seE5XOVpocU5DV09oNmVpWWhqNjR6STVWREw0SkFkUmFFSThFMQpoSHFEZ3pGZ1Y0YS9VZWlsQkQ2Nkh2K2N0Nk9rc2JvNzZyNHJqREptbTNOVE5DMEg3VUVtTFVjM2pabmgxOUswCnlWNWk0anpIWVZIcmhLUUkvNFpFc0ppWlU3L1o1WnVQQ2wrMUk5UjRzcHZ4SXpnOEpoakkwTVRyaXN1bHVSc3gKVTJEYlRRWjh1MlJyb0JTblQ3dTFMZ0RZaTk1d1lxUDlkMjYxeWNlblE5VmJyODNQeDR4N0NGbEN3anM2bW9mQQoxZC9VdWhzYWU1MEFIbjk2bzg1TnZCSytvTUowNTljUlVsMk43TUNIdlBXMndLVVJjTmpoRTN0UWY3NDNqYXZuCmhvNW1VbXRXT0hYV0x4a0l0bFRZb0hnVEtId0twUmNwWUE0dwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
                server: https://AB03FDEF04B5A25471EA8FB37DC719E9.gr7.us-east-1.eks.amazonaws.com
              name: arn:aws:eks:us-east-1:064274872851:cluster/neosec-exercise
            - cluster:
                server: ""
              name: neosec-exercise
            contexts:
            - context:
                cluster: arn:aws:eks:us-east-1:064274872851:cluster/neosec-exercise
                user: arn:aws:eks:us-east-1:064274872851:cluster/neosec-exercise
              name: arn:aws:eks:us-east-1:064274872851:cluster/neosec-exercise
              current-context: arn:aws:eks:us-east-1:064274872851:cluster/neosec-exercise
              kind: Config
              preferences: {}
              users:
              - name: arn:aws:eks:us-east-1:064274872851:cluster/neosec-exercise
                user:
                  exec:
                    apiVersion: client.authentication.k8s.io/v1alpha1
                    args:
                    - --region
                    - us-east-1
                    - eks
                    - get-token
                    - --cluster-name
                    - neosec-exercise
                    command: aws
                    env:
                    - name: AWS_PROFILE
                      value: aws-profile
                    interactiveMode: IfAvailable
                    provideClusterInfo: false


      # - name: Create Config File
      #   run: |
      #       echo $KUBECONFIG_FILE > config
      #       cat config
      #       cat config | base64 -d > config
      #       MY_STRING=$(cat config)
      #       MY_STRING="${MY_STRING//'%'/'%25'}"
      #       MY_STRING="${MY_STRING//$'\n'/'%0A'}"
      #       MY_STRING="${MY_STRING//$'\r'/'%0D'}"
      #       echo "::set-output name=content::$MY_STRING"
      #   shell: bash
      #   id: my_string
      #   env:
      #     KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'

      # - name: display string
      #   run: |
      #     echo "The string is: ${{ steps.my_string.outputs.content }}"

      - name: aws-cli
        run: pip3 install awscli
        shell: bash

      # - name: Deploy 
      #   uses: WyriHaximus/github-action-helm3@v2
      #   with:
      #     exec: helm upgrade --install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml
      #     kubeconfig: '${{ secrets.KUBE_CONFIG }}'

      - name: Deploy To Cluster
        run: helm upgrade --install yuvalpress-app ./charts/ --namespace yuvalpress -f ./charts/values.yaml